server:
  port: 8090

spring:
  user:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/user
      username: root
      password: pass
  department:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/department
      username: root
      password: pass

  autoconfigure:
    exclude= org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
